package com.ytc.mapper;

import java.util.List;

import com.ytc.model.TEatingHouse;

public interface TEatingHouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int deleteByPrimaryKey(Integer tEatingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int insert(TEatingHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int insertSelective(TEatingHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    TEatingHouse selectByPrimaryKey(Integer tEatingId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int updateByPrimaryKeySelective(TEatingHouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_eating_house
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int updateByPrimaryKey(TEatingHouse record);

    Integer queryCount();

    List<TEatingHouse> queryTEatingHouseList(int start, int pageSize);
}