package com.ytc.mapper;

import com.ytc.model.TUsers;

public interface TUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int deleteByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int insert(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int insertSelective(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    TUsers selectByPrimaryKey(Integer tId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int updateByPrimaryKeySelective(TUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_users
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    int updateByPrimaryKey(TUsers record);
}