package com.ytc.model;

public class TEatingVariety {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eating_variety.t_varity_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private Integer tVarityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eating_variety.t_varity_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private String tVarityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eating_variety.t_varity_price
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private Integer tVarityPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_eating_variety.t_eating_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private Integer tEatingId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eating_variety.t_varity_id
     *
     * @return the value of t_eating_variety.t_varity_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public Integer gettVarityId() {
        return tVarityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eating_variety.t_varity_id
     *
     * @param tVarityId the value for t_eating_variety.t_varity_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settVarityId(Integer tVarityId) {
        this.tVarityId = tVarityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eating_variety.t_varity_name
     *
     * @return the value of t_eating_variety.t_varity_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public String gettVarityName() {
        return tVarityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eating_variety.t_varity_name
     *
     * @param tVarityName the value for t_eating_variety.t_varity_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settVarityName(String tVarityName) {
        this.tVarityName = tVarityName == null ? null : tVarityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eating_variety.t_varity_price
     *
     * @return the value of t_eating_variety.t_varity_price
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public Integer gettVarityPrice() {
        return tVarityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eating_variety.t_varity_price
     *
     * @param tVarityPrice the value for t_eating_variety.t_varity_price
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settVarityPrice(Integer tVarityPrice) {
        this.tVarityPrice = tVarityPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_eating_variety.t_eating_id
     *
     * @return the value of t_eating_variety.t_eating_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public Integer gettEatingId() {
        return tEatingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_eating_variety.t_eating_id
     *
     * @param tEatingId the value for t_eating_variety.t_eating_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settEatingId(Integer tEatingId) {
        this.tEatingId = tEatingId;
    }
}