package com.ytc.model;

public class TUsers {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.t_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private Integer tId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.t_user_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private String tUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.t_user_money
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    private Integer tUserMoney;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.t_id
     *
     * @return the value of t_users.t_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public Integer gettId() {
        return tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.t_id
     *
     * @param tId the value for t_users.t_id
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settId(Integer tId) {
        this.tId = tId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.t_user_name
     *
     * @return the value of t_users.t_user_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public String gettUserName() {
        return tUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.t_user_name
     *
     * @param tUserName the value for t_users.t_user_name
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settUserName(String tUserName) {
        this.tUserName = tUserName == null ? null : tUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.t_user_money
     *
     * @return the value of t_users.t_user_money
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public Integer gettUserMoney() {
        return tUserMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.t_user_money
     *
     * @param tUserMoney the value for t_users.t_user_money
     *
     * @mbggenerated Tue Jan 11 14:08:22 CST 2022
     */
    public void settUserMoney(Integer tUserMoney) {
        this.tUserMoney = tUserMoney;
    }
}